### ISSUE TITLE
change url /admin nginx

### ISSUE THREAD

**Issue by aripjanovsh** [mickgeek/yii2-advanced-one-domain-config#1]
Hello,

How to change the path `/admin` to `/backend`  on NGINX

I tried to change the config 

```
....
location /backend{
        alias  /path/to/advanced/backend/web;
        try_files  $uri /backend/web/index.php?$args;

        # redirect to the page without a trailing slash (uncomment if necessary)
        #location = /admin/ {
        #    return  301 /admin;
        #}

        location ~* ^/backend/(.+\.php)$ {
            try_files  $uri /backend/web/$1?$args;
        }

        # avoid processing of calls to non-existing static files by Yii (uncomment if necessary)
        #location ~* ^/admin/(.+\.(css|js|jpg|jpeg|png|gif|bmp|ico|mov|swf|pdf|zip|rar))$ {
        #    try_files  $uri /backend/web/$1?$args;
        #}
}
...
```

It displays 404 error

**Comment by mickgeek** [comment]
The problem is in the `try_files` directive, it is very capricious.

In addition to changing the `admin` to the `backend` paths, you should make the following changes:
- The head `root` directive: from `/path/to/advanced` to `/path/to`;
- The `try_files` directives: from `/frontend/web` to `/advanced/frontend/web` and from `/backend/web` to `/advanced/backend/web`, respectively.
